#include<iostream>
#include<fstream>
#include<filesystem>
#include<vector>
#include<string>

std::string filename;
std::filesystem::path tmp_dir = "/tmp/bread/";
std::filesystem::path cpp_dir = "/tmp/bread/temp.cpp";
std::string cppname;
std::vector<std::string> file_contents;

int create_tmp_dir_if_not_exist() {
    try {
        if (!std::filesystem::is_directory(tmp_dir)) {
            std::filesystem::create_directory(tmp_dir);
            std::cout << "created tmp directory, first start?" << std::endl;
        }
    } catch (const std::filesystem::filesystem_error &e) {
        std::cout << "could not create tmp directory, " << e.what() << std::endl;
        return 1;
    }
    return 0;
}


int compile_to_cpp(std::string filename) {
    std::ifstream breadfile;
    std::ofstream cpp_file;

    breadfile.open(filename);
    if (!breadfile.is_open()) {
        std::cerr << "error opening file" << std::endl;
        throw 500;
        return 1;
    }
    std::string c;
    while (std::getline(breadfile, c)) {
        file_contents.push_back(c);
    } // save file into vector
    breadfile.close();
    cpp_file.open(cpp_dir);
    if (!cpp_file.is_open()) {
        std::cerr << "error creating temporary cpp file" << std::endl;
        throw 500;
        return 1;
    }
    cpp_file << "//transpiled from the bread programming language, do not edit this file\n#include<iostream>\nint main() {\n";
    for (std::string content : file_contents) {
        if (content.find("print/") == 0) {
            content.erase(0, 6);
            cpp_file << "std::cout << " << content << ";\n";
        }
    }
    cpp_file << "return 0;\n}\n";
    cpp_file.close();
    return 0;
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        std::cout << "no arguments given, enter filename to compile .bread file" << std::endl;
        return 1;
    } else {
        filename = argv[1];
    }
    create_tmp_dir_if_not_exist();
    try {
        compile_to_cpp(filename);
    } catch (int ercode) {
        return 1;
    }
    return 0;
}